def plot(name)
  # read in the file
  file = File.open("plots/#{name}.plot") {|f| f.read}

  # determine which figures it makes.
  figures = determine_figures(file)

  # just assume the deps are the files in the subdirectory
  deps = FileList["#{name}/**/*.dat", "#{name}/*.csv"]

  # make tasks for each of the figures
  figures.each do |figure|

    # first, the eps figure
    file figure => ["plots/#{name}.plot", 'figures'] + deps do
      sh "gnuplot 'plots/#{name}.plot'"
    end

    # next the pdf
    pdf_task(figure)
  end
end

def determine_figures(file_contents)
  figures = []
  file_contents.scan(/^set output "([^"]+)"/) do |fig|
    figures << fig
  end
  figures.flatten
end

def pdf_task(figure)
  pdf = figure.pathmap("%X.pdf")

  file pdf => figure do
    sh "epstopdf '#{figure}'"
  end

  task :make_figures => pdf
end

task :default => :make_figures

directory 'figures'

FileList["plots/**/*.plot"].pathmap('%n').each do |figure|
  plot figure
end

twod_plots = {
  'het_bosch' => 141,
  'hom_bosch' => 141,
  'het_control' => 157,
  'hom_control' => 157,
  'het_workman' => 181,
  'hom_workman' => 181,
}

twod_plots.each do |name, start|
  directory "04_plots/#{name}"

  [1,2,3,4].each do |t|
    fn = "/media/My Passport/afsheets/%s_jpgs/RA%06d.jpg" % [name, (t*400)+start ]
    file "04_plots/#{name}/#{name}_#{t}.jpg" => ["04_plots/#{name}", fn] do |t|
      cp fn, t.name
    end
    task :twod_figure => "04_plots/#{name}/#{name}_#{t}.jpg"
  end
end

