# Rakefile for hzhangpg02.ph.man.ac.uk
# Rakefile
# Jonathan D. Stott <jonathan.stott@gmail.com>
load 'rakelib/ecg.rake'
require 'rake/clean'

# ECG stuff
PLOT_TEMPLATE = File.join('templates', 'ecg_plot.erb')

desc 'Generate all figures'
task :all => [:ecgs, :bsps]

task :default => :all

BSP_ROOT = "/media/My Passport/bsps/refined_atrial_meshes"

%w{all blood lungs thorax}.each do |c|
  dir = "bsp_#{c}"
  directory dir


  %w{0010 0015 0020 0025 0040 0060 0180 0200 0220}.each do |snapshot|
    fn = "refined_#{c}.#{snapshot}.png"
    file File.join(dir, fn) => [File.join(BSP_ROOT, c, 'pngs', fn), dir] do |t|
      cp t.prerequisites.first, t.name
      sh "mogrify -crop 500x500+70+70 '#{t.name}'"
    end

    task :bsps => File.join(dir, fn)
  end

  file "ecg_#{c}.dat" => File.join(BSP_ROOT, c, "#{c}.dat") do |t|
    cp t.prerequisites.first, t.name
  end

  [150].each do |freq|
    filtered_ecg "ecg_#{c}", freq
  end
end
