def plot_figure(name)
  file "figures/#{name}.pdf" => "figures/#{name}.eps" do
    sh "epstopdf figures/#{name}.eps"
  end

  file "figures/#{name}.eps" => ["plots/#{name}.plot", 'figures'] + FileList["#{name}/**/*.dat", "#{name}/*.csv"] do
    sh "gnuplot plots/#{name}.plot"
  end

  task :make_figures => "figures/#{name}.pdf"
end

task :default => :make_figures

directory 'figures'

%w{01_IV 03_REST}.each do |f|
  plot_figure(f)
end
